management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /api/application
spring:
  profiles:
    active: "${ACTIVE_PROFILE:dev}"
  application:
    name: Todo-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol:
            smtp
        debug:
          true
        smtp:
          auth: true
          starttls:
            enable: true
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    web: info
todo:
  security:
    patterns-for-all: /, /login, /register, /styles/**, /scripts/**, /images/**
    patterns-for-users: /todo, /todo/**, /todo**, /todo**/**, /exit, /account, /account/**, /notification, /notification/**, /notifications
    patterns-for-admins: /api, /api/**
  message:
    notification-subject: Todo Notification for %s!
    notification-text: Hello, %s!%nWe are happy to remind you about your Todos!%nDon't forget to finish them!%nYour da best Todo Support!
server:
  port: ${SERVER_PORT}