#Profile
ACTIVE_PROFILE: dev

#Database
DB_USERNAME: root
DB_PASSWORD: Mu18052007
DB_URL: jdbc:mysql://localhost:3306/newtodo_schema

#Mail
MAIL_USERNAME: newtodo01@gmail.com
MAIL_PASSWORD: uscy utwn nkjz fkml

#Server
SERVER_PORT: 8080