management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /api/application
spring:
  application:
    name: Todo-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mu18052007
    url: jdbc:mysql://localhost:3306/newtodo_schema
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jackson:
    serialization:
      indent-output: true
logging:
  level:
    web: info
todo:
  security:
    patterns-for-all: /, /login, /register, /styles/**, /scripts/**, /images/**
    patterns-for-users: /todo, /todo/**, /todo**, /todo**/**, /exit, /account, /account/**, /notification, /notification/**
    patterns-for-admins: /api, /api/**
  message:
    notification-text: Hello, %s!%nWe are happy to remind you about your Todos!%nDon't forget to finish them!%nYour da best Todo Support!