spring:
  application:
    name: Todo-App
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mu18052007
    url: jdbc:mysql://localhost:3306/newtodo_schema
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    web: info
todo:
  security:
    patterns-for-all: /, /**, /login, /register
    patterns-for-users: /todo, /todo/**, /todo**, /todo**/**, /exit, /account, /account/**